### ISSUE TITLE
Home - Read More buttons

### ISSUE THREAD

**Issue by jonahpriorities** [jakewelchert/Priorities-USA---static#14]
Make them just a text link, without border. Keep it left aligned with the paragraph.

**Comment by jonahpriorities** [comment]
Can we use the text only Read More style we already are using on The Latest page.

**Comment by jakewelchert** [comment]
I made note of this in the email but want to make sure it's here -- we feel the full button is better on desktop because it's a stronger call to action. Is this okay or would you still like changed?

**Comment by jonahpriorities** [comment]
Yes let's change. Looking at it we have the heading link and read more link. Not sure if the image is a link as well. We would prefer they tweet/fb share as primary CTA.

**Comment by jakewelchert** [comment]
Fixed across the board.
