### ISSUE TITLE
Global - footer - connect

### ISSUE THREAD

**Issue by jonahpriorities** [jakewelchert/Priorities-USA---static#18]
Can you match the regular and hover states to the header. Right now the hover goes very dark and its hard to see against the dark blue. I really like the header treatment and hope that gray state works on the background. If now can you try it as white that hovers to the light blue.

**Comment by jakewelchert** [comment]
The gray is hard to read on the dark blue. We can try white with a light blue hover, but I'll have to make the inline links have a bottom border since they'll be the same color.

**Comment by jakewelchert** [comment]
Changed to white with a light blue hover treatment. Feels more like the header now. Also decreased vertical spacing and changed copy size. Please review.
