### ISSUE TITLE
Homepage - The Latest - Category tags

### ISSUE THREAD

**Issue by jonahpriorities** [jakewelchert/Priorities-USA---static#20]
Can you separate the tags at the top of each post with a comma or some other element to differentiate. Right now they look like "Youth News" rather than "Youth" and "News".

**Comment by jakewelchert** [comment]
Good call. I'll try a vertical dash ( | ) and see how it looks.

**Comment by jakewelchert** [comment]
Added a vertical dash between date and category names. Added bullet between the category names. Looks much better.
