### ISSUE TITLE
Individual Category page

### ISSUE THREAD

**Issue by jonahpriorities** [jakewelchert/Priorities-USA---static#6]
I imagine this will follow very closely the wireframe for the blog page but could you show us a quick page that is just the "Press" Category tag. Again it won't be linked to in global nav.

**Comment by jakewelchert** [comment]
Jonah--do you need to see the individual post, or how it would look if you landed on The Latest feed page with Press selected?

**Comment by jonahpriorities** [comment]
What the page for posts sorted by an individual category would look like.
Right now the only use case is a Press category page. I imagine it looks
like The Latest blog page but with just one category tag at the top but
just want to have it to show around and confirm. Does that make sense?

**Comment by jakewelchert** [comment]
Since it's a page on the backend that is't linked, would it make since to not have category filtering?

**Comment by jonahpriorities** [comment]
Yes I think so. I was just thinking we would populate that page by selecting a Press category tag in the editor and just push those posts to the Press page and not the blog. But if there is a better way I will leave it up to you.

**Comment by jakewelchert** [comment]
Yeah, that will work too. I think we were both thinking the same thing but couldn't quite communicate it. It's either that or a completely different post type. Either way, I would just make the archive page without the filter so that's the only thing they'd see.

Good call.

**Comment by jakewelchert** [comment]
Sounds like we'll be creating a custom post type. So, it'll be like another blog on the backend.
