### ISSUE TITLE
Can we pin the top The Latest?

### ISSUE THREAD

**Issue by jonahpriorities** [jakewelchert/Priorities-USA---static#8]
New request: are we able to "pin" the top The Latest post on the homepage so it doesn't get replaced by newer content? I shared that the hero/mantle would essentially do this but there was a request to see if it is feasible to do this for the top Latest post as well.

**Comment by jakewelchert** [comment]
I will follow up with this. Going to check before I can promise anything. It should be doable. We would probably call it a featured post in WordPress so it stayed there at the top.

**Comment by jakewelchert** [comment]
Doable with Sticky Posts (WordPress plugin). Will review once we get the CMS hooked up.
